name: Windows2spec

on: 
  workflow_dispatch:
    inputs:
      ngrok:
        description: 'ngrok auth token'
        required: true
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install curl wget qemu-kvm -y
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          tar -xf ngrok-v3-stable-linux-amd64.tgz
          chmod +x ngrok
          ./ngrok config add-authtoken "${{ github.event.inputs.ngrok }}"
          nohup ./ngrok tcp --region ap 5900 &>/dev/null &
      - name: cài win và khởi chạy
        run: |
          sudo chmod 666 /dev/kvm
          sudo qemu-img create -f qcow2 /mnt/a.qcow2 60G
          wget -O win.iso https://dl.malwarewatch.org/windows/Windows-8.1-x64.iso
          wget -O driver.iso https://computernewb.com/isos/driver/virtio-win-0.1.240.iso
          sudo qemu-system-x86_64 -cpu host -smp sockets=1,cores=8,threads=2 -m 12G -device intel-hda -device hda-duplex  -vnc :0 -enable-kvm -drive file=/mnt/a.qcow2 -drive file=win.iso,media=cdrom -drive file=driver.iso,media=cdrom -device virtio-gpu-pci -device virtio-balloon-pci -device virtio-serial-pci -device virtio-rng-pci -device virtio-net-pci,netdev=n0 -netdev user,id=n0 -device qxl-vga,vgamem_mb=1024 /usr/share/ovmf/OVMF.fd
